name: BuildPulse Demo

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Tests
        run: mvn clean test

      - name: Upload Test Results To BuildPulse
        if: always()
        uses: BuildPulseLLC/test-reporter-action@v3
        with:
          api-token: ${{ secrets.BUILDPULSE_API_TOKEN  }}
          path: target/surefire-reports/*.xml
